export const UPDATE_BOOKING_STATUS = "UPDATE_BOOKING_STATUS"
export const BOOKING_ERROR = "BOOKING_ERROR"
export const CREATE_CUSTOMER = "CREATE_CUSTOMER"
export const CUSTOMER_ERROR = "CUSTOMER_ERROR"
export const CREATE_STAFF_AND_SALON_SCHEDULE = "CREATE_STAFF_AND_SALON_SCHEDULE"
export const STAFF_AND_SALON_SCHEDULE_ERROR = "STAFF_AND_SALON_SCHEDULE_ERROR"

export const GET_SALONSCHEDULE = "GET_SALONSCHEDULE"