export const UPDATE_BOOKING_STATUS = "UPDATE_BOOKING_STATUS"
export const BOOKING_ERROR = "BOOKING_ERROR"
export const CREATE_CUSTOMER = "CREATE_CUSTOMER"
export const CUSTOMER_ERROR = "CUSTOMER_ERROR"

export const GET_SALONSCHEDULE = "GET_SALONSCHEDULE"