create table customer (
                          id bigint generated by default as identity,
                          address varchar(255),
                          customername varchar(255),
                          full_name varchar(25),
                          password varchar(255),
                          pending boolean not null,
                          phone_number varchar(9),
                          primary key (id)
);

create table salon_schedule (
                                id bigint generated by default as identity,
                                staff_id bigint,
                                day_of_the_week varchar(255),
                                is_holiday boolean,
                                created_date timestamp,
                                last_modified_date timestamp,
                                primary key (id)
);

create table staff (
                       id bigint generated by default as identity,
                       address varchar(255),
                       full_name varchar(25),
                       password varchar(255),
                       pending boolean not null,
                       phone_number varchar(9),
                       staffname varchar(255),
                       primary key (id)
);

create table salon_booking (
                               id bigint generated by default as identity,
                               booking_date date,
                               booking_date_time timestamp,
                               booking_time time,
                               created_date timestamp,
                               customer_id bigint,
                               hair_cut_type integer,
                               last_modified_date timestamp,
                               staff_id bigint,
                               primary key (id)
);

insert into staff values(1, 'address', 'William', 'password', 0, '123456789', 'William');
insert into staff values(2, 'address', 'Jane', 'password', 0, '123456789', 'Jane');
insert into staff values(3, 'address', 'Mark', 'password', 0, '123456789', 'Mark');

insert into salon_schedule values (1, 1, 'MONDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (2, 1, 'TUESDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (3, 1, 'WEDNESDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (4, 1, 'THURSDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (5, 1, 'FRIDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (6, 1, 'SATURDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (7, 1, 'SUNDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');

insert into salon_schedule values (8, 2, 'MONDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (9, 2, 'TUESDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (10, 2, 'WEDNESDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (11, 2, 'THURSDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (12, 2, 'FRIDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (13, 2, 'SATURDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (14, 2, 'SUNDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');

insert into salon_schedule values (15, 3, 'MONDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (16, 3, 'TUESDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (17, 3, 'WEDNESDAY', 0, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (18, 3, 'THURSDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (19, 3, 'FRIDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (20, 3, 'SATURDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');
insert into salon_schedule values (21, 3, 'SUNDAY', 1, '2022-03-23 00:00:00', '2022-03-23 00:00:00');