server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mysql://whs-database.cvlzvh6b6bzg.us-east-1.rds.amazonaws.com:3306/whs_database
    username: admin
    password: Cloudcomputing!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
  flyway:
    enabled: false
    validateOnMigrate: false
    baselineOnMigrate: true
    encoding: UTF-8
    username: sa
    locations: filesystem:BackEnd/db/migration
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
logging:
    level:
      org.springframework: debug
      org.hibernate.SQL: info
      org.hibernate.type.descriptor.sql.BasicBinder: trace
